name: tests

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [7.4]
                fjord: [2.4.*]
                laravel: [7.*]
                stability: [prefer-lowest, prefer-stable]
                include:
                    - laravel: 7.*
                      testbench: 5.*

        name:
            P${{ matrix.php }} - L${{ matrix.laravel }} - FJ${{ matrix.fjord }}
            - ${{ matrix.stability }}

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.composer/cache/files
                  key:
                      dependencies-laravel-${{ matrix.laravel }}-php-${{
                      matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions:
                      dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite,
                      pdo_sqlite
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "aw-studio/fjord:${{ matrix.fjord }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-suggest

            - name: Execute tests
              run: vendor/bin/phpunit
